### ISSUE TITLE
Support Blank Firmware

### ISSUE THREAD

**Issue by binduwavell** [captdeaf/keybard#30]
When building a new board, it can help to use the blank firmware in order to run the matrix tester without outputting all sorts of mods and characters. This works in Vial but KeyBard doesn't show a board at all and will not load a valid KBI file.

See the Svalboard releases for sample blank firmwares.

**Comment by binduwavell** [comment]
I need to retest this. I also had some issues with loading my old KBI onto my new board, so I should test the blank firmware again.

**Comment by binduwavell** [comment]
I double checked and the blank firmware connects but does not show any keymap UI.

Error in JS Console is:

```
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'NaN')
    at renderMatrix (matrixtester.js:55:33)
    at Object.func (matrixtester.js:64:22)
    at runInitializers (util.js:317:35)
    at doStuff (main.js:75:3)
```

This may be a different ticket. I am able to upload my KBI but it fails to completely load. So I have a partial map without my macros. Not sure what else is incomplete...
